title: Savio Nguyen | Data Science Portfolio
description: Documenting my learning in Data Structures
theme: jekyll-theme-midnight

author:
  name: Savio Nguyen

github_url: "https://github.com/savionguyen6"
linkedin_url: "https://www.linkedin.com/in/savio-nguyen-5562ab33b/"
